### ISSUE TITLE
How to use an existing VPC? Terraform plan not picking up variables - i.e for wireguard-with-cillium example

### ISSUE THREAD

**Issue by AlectoTheFirst** [aws-ia/terraform-aws-eks-blueprints#1467] opened 2023-02-28 12:11 UTC
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have to deploy multiple EKS clusters, however all the VPCs, ACLs, Route Tables, Subnet-Ids are configured by another team.
How can I specify an existing VPC to use in any of the  blueprint examples, e.g wireguard-with-cilium? 

I tried "terraform import module.vpc.aws_vpc.this myvpcid"  which results in multiple "invalid provider configuration" errors for provider helm, kubernetes and kubectl.  Adding a default = myvpcid into the variables.tf is getting ignored by terraform plan. 

Same with filling the variables for private_subnet_ids, public_subnet_ids, terraform plan is not reflecting any input

I definitely seem to have some gaps in understanding how the blueprint works, any hint in the right direction would be greatly appreciated

Maybe its possible to have the "Getting Started" Guide amended with some example on how to leverage existing network resources?

Thanks a lot
Alecto

**Comment by bryantbiggs** [comment] 2023-02-28 12:39
To use existing resources, you don't re-import them into state because this would mean you want to assume control of them. Instead, I believe you just want to use them. Therefore, you simply supply the values for the appropriate inputs such as `vpc_id`, `subnet_ids`, and `control_plane_subnet_ids`

**Comment by AlectoTheFirst** [comment] 2023-03-01 14:39
> Therefore, you simply supply the values for the appropriate inputs such as `vpc_id`, `subnet_ids`, and `control_plane_subnet_ids`

that is what i am trying and it is not picking up the values supplied in variables.tf 
terraform plan insists of creating a new VPC as well as new Subnets.

**Comment by bryantbiggs** [comment] 2023-03-01 14:40
Unfortunately, without seeing your full configuration, I would just be guessing at this point as to what might be happening in your use case

**Comment by AlectoTheFirst** [comment] 2023-03-01 14:44
```
variable "vpc_id" {
  description = "VPC Id"
  type        = string
  default     = "vpc-0475251dd51d23661"
}
variable "private_subnet_ids" {
  description = "List of private subnets Ids for the cluster and worker nodes"
  type        = list(string)
  default     = ["subnet-07c1aa2d11cbe5bd10", "subnet-0b692e9dc53c18b8b", "subnet-073483d4abd824e28" ]
}
 
variable "public_subnet_ids" {
  description = "List of public subnets Ids for the worker nodes"
  type        = list(string)
  default     = ["subnet-026453931b8f12e71e", "subnet-0375d408b2ee2bccb", "subnet-0ef5d2fe4fa2025b1"]
}
 
variable "control_plane_subnet_ids" {
  description = "A list of subnet IDs where the EKS cluster control plane (ENIs) will be provisioned. Used for expanding the pool of subnets used by nodes/node groups without replacing the EKS control plane"
  type        = list(string)
  default     = ["subnet-026453931b8f7e71e", "subnet-0375d408b2ee9bccb", "subnet-0ef5d2fe4fa20a5b1"]
}
```

Should that be sufficient for terraform plan to pick up or do i need to somewhere disable vpc creation? i added the above in variables.tf in the vpc-cni-custom-networking example (also tried changing the variables.tf in rootpath)

**Comment by bryantbiggs** [comment] 2023-03-01 14:44
thats just a few variables - where are the used and how? Please follow the issue template provided which requires a reproduction

**Comment by AlectoTheFirst** [comment] 2023-03-01 14:48
You wrote to just reuse the existing IDs but i am trying to figure out at which place i need to add them get them picked up.
The aboves variables are already set in the variables.tf with default = [], so i just added my subnet-ids and vpc_id to it hoping that would do it.

This is why i was asking to have the documentation extended on how to use the blueprints on existing resources.

**Comment by bryantbiggs** [comment] 2023-03-01 14:50
please see from our standard issue template the requirements for issues below
![image](https://user-images.githubusercontent.com/10913471/222174897-7fee7ad9-982a-43e0-84e1-0d1ab87d9ee8.png)

Closing for now until a proper reproduction can be provided

**Closed by bryantbiggs** 2023-03-01 14:50 UTC

**Comment by AlectoTheFirst** [comment] 2023-03-01 15:00
wow, can you be even more rude and maybe just answer my question. The variables above are from your own code, i did not add them, i just changed the empty default = [] to include my IDs.
