### ISSUE TITLE
aws-load-balancer-controller not authorized to addTags on Target groups

### ISSUE THREAD

**Issue by yardenw-terasky** [aws-ia/terraform-aws-eks-blueprints#1683] opened 2023-07-11 09:48 UTC
## Description
Hey, Seems like AWS made an API change on the requirement of explicit elasticloadbalancing:AddTags permission for creating resources, and potentially affect new AWS accounts. As described [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692)

It can be easily fixed by applying the new iam-policy.json template provided [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json) 

## Versions

- Module version [4.31]:

- Terraform version: 1.52
- Provider version(s): AWS - 4.61

- EKS version: 1.24

## Reproduction Code [Required]
simply: 

module "kubernetes_addons" {
  source               = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.28.0/modules/kubernetes-addons"
  eks_cluster_id       = var.eks_cluster_name
  eks_cluster_endpoint = var.eks_cluster_endpoint
  eks_oidc_provider    = var.eks_oidc_provider
  eks_cluster_version  = var.eks_cluster_version

  enable_aws_load_balancer_controller = var.enable_aws_load_balancer_controller
}

## Expected behaviour
aws-load-balancer-controller should detect ingress resources and expose a load balancer according to the configuration

## Actual behaviour
failed to reconcile due to policy issues mentioned

I know for a fact that not all AWS accounts are impacted by this, but for some reason new accounts do.

Thanks!

**Comment by bryantbiggs** [comment] 2023-07-11 11:09
duplicate of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/200

**Closed by bryantbiggs** 2023-07-11 11:09 UTC

**Comment by psolarcz** [comment] 2023-09-08 12:55
Hi @bryantbiggs ,
Why is this considered as duplicate? Don't `terraform-aws-eks-blueprints-addons` and `terraform-aws-eks-blueprints` maintain IAM policies separately?

[Statement](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/v1.7.2/main.tf#L1134-L1149) seems to be missing in https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.32.1/modules/kubernetes-addons/aws-load-balancer-controller/data.tf

**Comment by psolarcz** [comment] 2023-09-08 13:17
Are you talking about v5 or it applies also to v4?

**Comment by bryantbiggs** [comment] 2023-09-08 13:22
v4 is no longer supported so this is in reference to v5
