### ISSUE TITLE
Add the openmatch add-on in the modules

### ISSUE THREAD

**Issue by sdpoueme** [aws-ia/terraform-aws-eks-blueprints#1571] opened 2023-04-27 18:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

The EKS blueprint supports Agones. Many customers are using Agones with OpenMatch to have an end-to-end solution for matchmaking, game servers allocation and game sessions placement. Customers will benefit from having OpenMatch as a module that can be enabled in the add-ons. 

#### Describe the solution you would like

Include OpenMatch as add-on and give the ability to pass a custom helm values file in the Terraform code. 

#### Describe alternatives you have considered

Install OpenMatch manually using the Helm command line.

**Comment by bryantbiggs** [comment] 2023-04-27 18:42
duplicate of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/97

**Closed by bryantbiggs** 2023-04-27 18:42 UTC

**Comment by sdpoueme** [comment] 2023-04-27 18:46
Thanks Bryant, I did not realized I submitted twice.

**Comment by bryantbiggs** [comment] 2023-04-27 18:59
no worries, in your defense we moved the issue on ya!
