### ISSUE TITLE
[Karpenter] Rule with the name already exists on this event bus.

### ISSUE THREAD

**Issue by dtherhtun** [aws-ia/terraform-aws-eks-blueprints#1482] opened 2023-03-07 10:54 UTC
## Description

We cannot create Event bridge rules when we deploy more than one cluster in the same region with this option. `karpenter_enable_spot_termination_handling = true`

## Versions

- Module version [Required]:
v4.25.0
- Terraform version:
v1.3.9

- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.53.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Reproduction Code [Required]

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/e0e9aeb7ea785613cf794d524f79bcf5929bb6b8/modules/kubernetes-addons/karpenter/main.tf#L40

## Expected behavior

should be able to create more than one cluster in the same region without conflict with the resources naming

## Actual behavior
`Rule with the name already exists on this event bus.`

**Comment by askulkarni2** [comment] 2023-03-14 23:04
As mentioned, this is dupe of #1471

**Closed by askulkarni2** 2023-03-14 23:04 UTC
Labels: bug
