### ISSUE TITLE
Karpenter not working

### ISSUE THREAD

**Issue by bala151187** [aws-ia/terraform-aws-eks-blueprints#505] opened 2022-05-04 11:31 UTC
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.3

### What is your environment, configuration and the example used?

I see new instance coming up and getting terminated as soon as it get spin up.
karpenter version - v0.9.0

```
Controller logs
	INFO	controller	Launched instance: i-0ec9c7164b6b38344, hostname: ip-192-168-71-89.ec2.internal, type: t3a.2xlarge, zone: us-east-1f, capacityType: on-demand	{"commit": "a7e26e6", "provisioner": "default"}
2022-05-04T04:29:14.066Z	INFO	controller	Created node with 5 pods requesting {"cpu":"5125m","pods":"7"} from types c4.2xlarge, c6i.2xlarge, c5.2xlarge, c5a.2xlarge, c6a.2xlarge and 226 other(s)	{"commit": "a7e26e6", "provisioner": "default"}
2022-05-04T04:29:14.091Z	INFO	controller	Waiting for unschedulable pods	{"commit": "a7e26e6"}
2022-05-04T04:29:26.285Z	INFO	controller.termination	Cordoned node	{"commit": "a7e26e6", "node": "ip-192-168-71-86.ec2.internal"}
2022-05-04T04:29:26.305Z	DEBUG	controller.eviction	Evicted pod	{"commit": "a7e26e6", "pod": "default/inflate-6b88c9fb68-wm4z9"}
2022-05-04T04:29:26.319Z	DEBUG	controller.eviction	Evicted pod	{"commit": "a7e26e6", "pod": "default/inflate-6b88c9fb68-sgwhm"}
2022-05-04T04:29:26.338Z	DEBUG	controller.eviction	Evicted pod	{"commit": "a7e26e6", "pod": "default/inflate-6b88c9fb68-ttxw9"}
2022-05-04T04:29:26.363Z	DEBUG	controller.eviction	Evicted pod	{"commit": "a7e26e6", "pod": "default/inflate-6b88c9fb68-pdnls"}
2022-05-04T04:29:26.387Z	DEBUG	controller.eviction	Evicted pod	{"commit": "a7e26e6", "pod": "default/inflate-6b88c9fb68-5lxlh"}
2022-05-04T04:29:26.526Z	INFO	controller.termination	Deleted node	{"commit": "a7e26e6", "node": "ip-192-168-71-86.ec2.internal"}
2022-05-04T04:29:27.429Z	INFO	controller	Batched 5 pod(s) in 1.094765385s	{"commit": "a7e26e6"}
2022-05-04T04:29:29.783Z	INFO	controller	Launched instance: i-010de8fa52f4b0144, hostname: ip-192-168-08-182.ec2.internal, type: t3a.2xlarge
```
I manually created an instance using the lauchtemplate created by eksctl and got into the box for troubleshooting .
i saw kubelet service wasn't due to swap-off issue .. so i executed swapoff -a command and restarted the service . kubelet was running fine ..

But why is it like that .. Kindly help on the troubleshooting part

### What did you do and What did you see instead?

Karpenter shou;d create new instance for cluster

**Comment by bryantbiggs** [comment] 2022-05-04 14:51
Hi @bala151187 - could you kindly describe your current setup and steps you took before you run into the issue? Are you using the example blueprint https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter ?

**Comment by bryantbiggs** [comment] 2022-05-04 16:02
Can you share your configuration @bala151187 so I can see what you have configured and try reproducting by provisioning

**Comment by bala151187** [comment] 2022-05-04 16:14
> Can you share your configuration @bala151187 so I can see what you have configured and try reproducting by provisioning

```
# Complete eks module examples
# https://github.com/terraform-aws-modules/terraform-aws-eks/blob/dc8a6eecddc2c6957ba309a939ee46f39b946461/examples/complete/main.tf

module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_version = var.cluster_version
  cluster_name    = var.eks_cluster_name
  vpc_id          = var.vpc_id
  subnet_ids      = var.subnet_ids
  cluster_endpoint_private_access = var.cluster_endpoint_private_access
  cluster_endpoint_public_access  = var.cluster_endpoint_public_access
  enable_irsa     = var.enable_irsa
  tags            = var.tags

  # aws-auth configmap
  # https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting_iam.html#security-iam-troubleshoot-cannot-view-nodes-or-workloads
  manage_aws_auth_configmap = true
  aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::XXXXXXXXXXX:role/AWSReservedSSO_DevOpsAccess_1b66b06d544934bs"
      username = "AWSReservedSSO_DevOpsAccess_1b66b06d544934bs"
      groups   = ["system:masters"]
    }
  ]
}


module "eks_managed_node_groups"  {
  count           = length(var.node_group_name)
  source          = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  name            = element(var.node_group_name, count.index) #name_prefix to be in the range (1 - 38)
  use_name_prefix = var.use_name_prefix
  cluster_name    = var.eks_cluster_name
  cluster_version = var.cluster_version
  vpc_id          = var.vpc_id
  subnet_ids      = var.private_subnet_ids
  vpc_security_group_ids = [
    module.eks.cluster_primary_security_group_id,
    module.eks.cluster_security_group_id,
  ]
  instance_types = var.instance_types
  min_size        = var.min_size
  max_size        = var.max_size
  desired_size    = var.desired_size
  ami_type        = var.ami_type
  platform        = var.platform
  tags            = var.tags
  timeouts        = var.timeouts
  key_name        = var.key_name
  /* Quick reference parameters which can be passed to this module
  
  extend_config = {
    bootstrap_extra_args = "--kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot'"
  }
  capacity_type  = "SPOT"
  taints = {
    dedicated = {
      key    = "dedicated"
      value  = "gpuGroup"
      effect = "NO_SCHEDULE"
    }
  }
  */
}

resource "aws_eks_identity_provider_config" "oidc" {
  cluster_name = var.eks_cluster_name
  
  oidc {
    identity_provider_config_name = var.identity_provider_config_name
    client_id                     = var.client_id
    issuer_url                    = var.issuer_url
  }
}

module "eks_blueprints_kubernetes_addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.0.3"
  eks_cluster_id = module.eks.cluster_id

#   EKS Addons
#   enable_amazon_eks_vpc_cni            = true
#   enable_amazon_eks_coredns            = true
#   enable_amazon_eks_kube_proxy         = true
#   enable_amazon_eks_aws_ebs_csi_driver = true

#   K8s Add-ons
    # enable_argocd                       = true
    # enable_cluster_autoscaler           = true
    # enable_aws_for_fluentbit            = true
    # enable_metrics_server               = true
    # enable_prometheus                   = true
    # enable_ingress_nginx                = true
    # enable_vpa                          = true
    # enable_external_dns                 = true
    # enable_cert_manager                 = true
    # enable_kubernetes_dashboard         = true
    # enable_vault                        = true
    enable_karpenter                      = true
    karpenter_helm_config = {
      version   = "0.9.0"
      #   values = [templatefile("${path.module}/values.yaml", {
      #   node_iam_instance_profile = module.eks.cluster_iam_role_name
      # })]
    }
}

data "kubectl_path_documents" "karpenter_provisioners" {
  pattern = "${path.module}/provisioners/*.yaml"
  vars = {
    iam-instance-profile-id = "karpenter-lab-provisioner"
  }
}

resource "kubectl_manifest" "karpenter_provisioner" {
  for_each  = toset(data.kubectl_path_documents.karpenter_provisioners.documents)
  yaml_body = each.value

  depends_on = [module.eks_blueprints_kubernetes_addons]
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    token                  = data.aws_eks_cluster_auth.cluster.token
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  }
}
```
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: ${iam-instance-profile-id}
    subnetSelector:
      karpenter.sh/discovery: lab
    securityGroupSelector:
      karpenter.sh/discovery: lab
  ttlSecondsAfterEmpty: 30
```

**Comment by bryantbiggs** [comment] 2022-05-04 18:21
Since you are using a mix of blueprints and other modules, the following works for me:

```hcl
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.72"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.10"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.4.1"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14"
    }
  }
}

provider "aws" {
  region = local.region
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_id]
  }
}

provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false
  apply_retry_count      = 10

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_id]
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      command     = "aws"
      # This requires the awscli to be installed locally where Terraform is executed
      args = ["eks", "get-token", "--cluster-name", module.eks.cluster_id]
    }
  }
}

locals {
  name            = "test"
  cluster_version = "1.21"
  region          = "us-east-1"

  tags = {
    Example    = local.name
    GithubRepo = "terraform-aws-eks"
    GithubOrg  = "terraform-aws-modules"
  }
}

data "aws_caller_identity" "current" {}

################################################################################
# EKS Module
################################################################################

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.20"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  # Required for Karpenter role
  enable_irsa = true

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  node_security_group_additional_rules = {
    ingress_nodes_karpenter_port = {
      description                   = "Cluster API to Nodegroup for Karpenter"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }

  node_security_group_tags = {
    # NOTE - if creating multiple security groups with this module, only tag the
    # security group that Karpenter should utilize with the following tag
    # (i.e. - at most, only one security group should have this tag in your account)
    "karpenter.sh/discovery" = local.name
  }

  # We only need one node to get Karpenter up and running. This ensures core
  # services such as VPC CNI, CoreDNS, etc. are up and running so that Karpetner
  # can be deployed and start managing any additional compute capacity requirements
  eks_managed_node_groups = {
    initial = {
      instance_types        = ["t3.medium"]
      create_security_group = false

      min_size     = 1
      max_size     = 1
      desired_size = 1

      iam_role_additional_policies = [
        # Required by Karpenter
        "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      ]

      tags = {
        "karpenter.sh/discovery" = local.name
        }
    }
  }

  tags = local.tags
}


module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 4.20"

  role_name                          = "karpenter-controller-${local.name}"
  attach_karpenter_controller_policy = true

  karpenter_controller_cluster_id = module.eks.cluster_id
  karpenter_controller_node_iam_role_arns = [
    module.eks.eks_managed_node_groups["initial"].iam_role_arn
  ]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}

resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${local.name}"
  role = module.eks.eks_managed_node_groups["initial"].iam_role_name
}

module "addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.0.4"

  eks_cluster_id = module.eks.cluster_id

  enable_karpenter = true
  karpenter_helm_config = {
    version = "0.9.0"
    set = [
      {
        name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        value = module.karpenter_irsa.iam_role_arn
        }, {
        name  = "clusterName"
        value = module.eks.cluster_id
        }, {
        name  = "clusterEndpoint"
        value = module.eks.cluster_endpoint
        }, {
        name  = "aws.defaultInstanceProfile"
        value = aws_iam_instance_profile.karpenter.name
      }
    ]
  }
}

resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
    limits:
      resources:
        cpu: 1000
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags:
        karpenter.sh/discovery: ${local.name}
    ttlSecondsAfterEmpty: 30
  YAML

  depends_on = [
    module.addons
  ]
}

################################################################################
# Supporting Resources
################################################################################

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = local.name
  cidr = "10.0.0.0/16"

  azs             = ["${local.region}a", "${local.region}b", "${local.region}c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    # Tags subnets for Karpenter auto-discovery
    "karpenter.sh/discovery" = local.name
  }

  tags = local.tags
}
```

**Comment by bala151187** [comment] 2022-05-04 21:36
thanks @bryantbiggs that was helpful .. I'm so close to make this work ..`Karpenter_Controller_Policy` is not having enough permission to launch instance .. if i attach `admin access` it works .. so not sure what modification is required for `Karpenter_Controller_Policy` .. is there any way you could tell me 
this is wat the policy has got - https://github.com/terraform-aws-modules/terraform-aws-iam/blob/v4.24.0/modules/iam-role-for-service-accounts-eks/policies.tf#L511 
```
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 4.15"

  role_name                          = "karpenter-controller-${local.name}"
  attach_karpenter_controller_policy = true

  karpenter_controller_cluster_id = module.eks.cluster_id
  karpenter_controller_node_iam_role_arns = [
    module.eks_managed_node_groups[0].iam_role_arn
  ]
  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}

resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${local.name}"
  role = module.eks_managed_node_groups[0].iam_role_name
}

resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "0.8.1"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter_irsa.iam_role_arn
  }

  set {
    name  = "clusterName"
    value = module.eks.cluster_id
  }

  set {
    name  = "clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter.name
  }
}
```

**Comment by bryantbiggs** [comment] 2022-05-04 23:23
@bala151187 does your provisioner  have this tag specified
```yaml
tags:
  karpenter.sh/discovery: ${local.name}
```

**Comment by bala151187** [comment] 2022-05-05 03:15
> @bala151187 does your provisioner have this tag specified
> 
> ```yaml
> tags:
>   karpenter.sh/discovery: ${local.name}
> ```

yes . it does

```
cat <<EOF | kubectl apply -f -
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: lab
    securityGroupSelector:
      karpenter.sh/discovery: lab
    tags:
      karpenter.sh/discovery: lab
  ttlSecondsAfterEmpty: 30
EOF
```

**Comment by bala151187** [comment] 2022-05-06 03:09
Adding these policies fixed the issue 
```
      "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt",
                "kms:GenerateDataKey*",
                "kms:CreateGrant",
                "kms:DescribeKey"
```

**Comment by vara-bonthu** [comment] 2022-05-06 05:13
@bala151187 You can use this variable to pass additional policies to IRSA module. https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/ded4350705b0f26b2c2512eba17d5d4f709816eb/modules/kubernetes-addons/variables.tf#L575

with this example

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/ded4350705b0f26b2c2512eba17d5d4f709816eb/examples/karpenter/main.tf#L197

**Comment by bala151187** [comment] 2022-05-06 15:56
> @bala151187 You can use this variable to pass additional policies to IRSA module.
> 
> https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/ded4350705b0f26b2c2512eba17d5d4f709816eb/modules/kubernetes-addons/variables.tf#L575
> 
> with this example
> 
> https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/ded4350705b0f26b2c2512eba17d5d4f709816eb/examples/karpenter/main.tf#L197
> 
> Checkout this detailed doc on how to use Karpenter with EKS Blueprints. Let us know if its missing any info
> 
> https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/karpenter/

Sure i will give a shot .. so far . i handled it using below code 
```
resource "aws_iam_policy" "policy" {
  name        = "kms-policy-karpenter"
  description = "kms policy for karpenter"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt",
        "kms:GenerateDataKey*",
        "kms:CreateGrant",
        "kms:DescribeKey"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "karpenter-kms-attach" {
  role       = "karpenter-controller-${var.eks_cluster_name}"
  policy_arn = aws_iam_policy.policy.arn
}
```

**Comment by vara-bonthu** [comment] 2022-05-13 13:27
@bala151187 Are we good to close this issue now?

**Closed** 2022-05-13 16:10 UTC
Labels: bug
