### ISSUE TITLE
Private Repository

### ISSUE THREAD

**Issue by chielvis01** [aws-ia/terraform-aws-eks-blueprints#1476] opened 2023-03-03 21:21 UTC
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

When I fork these repos into a private repository:

https://github.com/aws-ia/terraform-aws-eks-blueprints
https://github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0
https://github.com/aws-samples/eks-blueprints-add-ons.git
https://github.com/aws-samples/eks-blueprints-workloads.git 

│ Error: Failed to download module
│ 
│ Could not download module "eks_blueprints" (main.tf:23) source code from "https://echi01:xxxxx@github.com:/chielvis01/blueprint-replica": error downloading
│ 'https://echi01:xxxxx@github.com:/chielvis01/blueprint-replica': bad response code: 404

Q: how do I pass in the password or the secret_string to authenticate my private repos. 
     Note that when I fork the repos and leave them private, everything works fine.

**Comment by askulkarni2** [comment] 2023-03-14 23:03
Duplicate of #1477

**Closed by askulkarni2** 2023-03-14 23:03 UTC
