### ISSUE TITLE
How can I ignore userdata changes for managed node group?

### ISSUE THREAD

**Issue by leonidkhelemes** [aws-ia/terraform-aws-eks-blueprints#1597] opened 2023-05-09 14:15 UTC
I'm using managed node groups with launch templeyts.
The issue is that I have user data and during different TF applies base64 data changes without actually start script change and terraform wants to create new launch template version and recreate all nodes in this node group.
```
  # module.eks_blueprints.module.aws_eks_managed_node_groups["mg_gpu"].aws_launch_template.managed_node_groups[0] will be updated in-place
  ~ resource "aws_launch_template" "managed_node_groups" {
      ~ user_data               = "AAAAAAAAAAAAAAAAAAAAAAAA" -> "BBBBBBBBBBBBBBBBBBBBBBB"
```
How can I avoid that? I'm thinking to add lifecycle ignore to the launch template user data, but not sure how to write it correctly.

**Comment by bryantbiggs** [comment] 2023-05-09 21:18
can you share what your configuration is currently that reproduces this issue

**Comment by leonidkhelemes** [comment] 2023-05-10 09:03
If I apply the recreation it doesn't show that userdata changed for some time after that, but after hours or one day terraform again show that userdata has been changed (actually it's not)
```
module "eks_blueprints" {
  source          = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.27.0"
  cluster_name    = local.cluster_name
  cluster_version = "1.26"

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  managed_node_groups = {   
    mg_gpu = {
      node_group_name = "mng-spot-gpu"
      ami_type        = "AL2_x86_64_GPU"
      instance_types  = ["g4dn.xlarge"]
      capacity_type   = "SPOT"
      min_size        = 3
      max_size        = 10
      desired_size    = 3
      create_iam_role = false # Changing `create_iam_role=false` to bring your own IAM Role
      iam_role_arn    = aws_iam_role.managed_ng.arn
      subnet_ids      = module.vpc.private_subnets

      # Launch template configuration
      create_launch_template = true              # false will use the default launch template
      launch_template_os     = "amazonlinux2eks" # amazonlinux2eks or bottlerocket

      pre_userdata           = <<-EOT
        yum install -y cri-tools
        crictl pull docker.io/semitechnologies/qna-transformers:bert-large-uncased-whole-word-masking-finetuned-squad-1.5.0
        ECR_REGION=us-east-1
        ECR_PASSWORD=$(aws ecr get-login-password --region $ECR_REGION)
        crictl pull --creds "AWS:$ECR_PASSWORD" 123456789.dkr.ecr.us-east-1.amazonaws.com/weaviate-modules:msmarco-minilm-l-6-v3-1.0.0
      EOT

      k8s_labels = {
        "k8s.amazonaws.com/accelerator" = "nvidia-tesla-t4"
      }
    }
  }
  platform_teams = {
    admin = {
      users = [
			data.aws_caller_identity.current.arn,
      ]
    }
  }

  # List of Additional roles admin in the cluster
  map_roles = [
    {
      username = "developers-role"  # The user name within Kubernetes to map to the IAM role
      groups   = ["system:masters"] # A list of groups within Kubernetes to which the role is mapped; Checkout K8s Role and Rolebindings
    }
  ]

  tags = local.tags
}
```

**Comment by leonidkhelemes** [comment] 2023-05-23 08:18
@bryantbiggs any ideas?

**Comment by bryantbiggs** [comment] 2023-05-24 14:24
I suspect this is due to the ECR credentials which will change as they expire but not 100% certain on that. however, this is unrelated to the module and seems to be specific to the user data you are supplying to the module

**Comment by bryantbiggs** [comment] 2023-06-02 23:47
closing this for now, please let us know if there are any additional questions

**Closed by bryantbiggs** 2023-06-02 23:47 UTC
Labels: question
