### ISSUE TITLE
[Bug]: Launch template error causing EC2 nodes to fail joining the node group properly

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#428] opened 2022-04-19 21:42 UTC
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

34921232356fb69b5a41094246d488c37c596d97

### What is your environment, configuration and the example used?

- Terraform 1.1.7

```hcl
module "eks_blueprints" {
  source  = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=34921232356fb69b5a41094246d488c37c596d97"

  org               = var.org
  tenant            = var.tenant
  environment       = var.environment
  zone              = var.zone
  tags              = var.tags

  // NOTE: Add-ons are not updated automatically when the cluster is updated.
  // You will need to do this at the appropriate time for each addon, if it is required.
  // See: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/index.md
  terraform_version = var.terraform_version

  # KMS
  cluster_kms_key_additional_admin_arns = var.cluster_kms_key_additional_admin_arns

  # Auth
  map_roles         = var.map_roles
  application_teams = var.application_teams
  platform_teams    = var.platform_teams
  
  # EKS Cluster VPC and Subnets
  vpc_id             = local.vpc_id
  private_subnet_ids = local.private_subnet_ids
  //public_subnet_ids  = local.public_subnet_ids

  # EKS CONTROL PLANE VARIABLES
  cluster_version                  = var.cluster_version
  cluster_endpoint_private_access  = false
  cluster_endpoint_public_access   = true

  # EKS MANAGED NODE GROUPS
  managed_node_groups = {
  ondemand_v1 = {
    node_group_name = "ondemand_v1"

    create_launch_template  = true
    launch_template_os      = "amazonlinux2eks"

    instance_types = ["t3a.large"]
    subnet_type    = "private"
    ami_type       = "AL2_x86_64"
    capacity_type  = "ON_DEMAND"
    disk_size      = 50

    desired_size    = 1
    min_size        = 1
    max_size        = 4
    max_unavailable = 1
  }
}
}
```

### What did you do and What did you see instead?

This will produce 2 node groups, instead of 1.

![CleanShot 2022-04-19 at 14 32 52](https://user-images.githubusercontent.com/129629/164105622-a45939c3-1cfb-420a-9629-6657c3278bbd.png)

The node group created by the AWS blueprints module [aws-eks-managed-node-groups](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/aws-eks-managed-node-groups) appears to be correct (the user data looks good), but it also appears to be unused.

Instead, it appears that the underlying https://github.com/terraform-aws-modules/terraform-aws-eks is ALSO creating a launch template and that template is being used by the instance, but is broken.

This template https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/linux_user_data.tpl is being used and is creating multiple bootstrap lines, which is causing the script to fail and therefore causing the node group to fail.

This is what the incorrect script looks like:

![CleanShot 2022-04-19 at 14 40 14](https://user-images.githubusercontent.com/129629/164106681-475eb986-4bc4-4a91-82ce-fea546419ca8.png)

**Comment by spkane** [comment] 2022-04-19 21:43
We are digging into the terraform modules to track the logic and figure out where the issue is, but any insight would be helpful, as it took us a while to determine that this is the underlying issue.

**Comment by spkane** [comment] 2022-04-19 23:46
I'm stumped for the moment...

**Comment by askulkarni2** [comment] 2022-04-20 04:32
Hi @spkane! I am going to try and reproduce the issue using the example and get back to you. We definitely don't see the double node group issue in our testing.

**Comment by askulkarni2** [comment] 2022-04-20 05:36
@spkane I am able to reproduce the issues you are reporting. We will debug the root cause and have a fix prepared.

**Comment by askulkarni2** [comment] 2022-04-20 06:11
I've traced the EC2 node failure to join the cluster issue to https://github.com/awslabs/amazon-eks-ami/pull/893. I see this in the `/var/log/cloud-init-out.log` on the instance.

```
mv: cannot stat ‘/etc/eks/iptables-restore.service’: No such file or directory
Exited with error on line 485
```

Also looks like @vara-bonthu already hit this [issue](https://github.com/awslabs/amazon-eks-ami/pull/893#issuecomment-1100063829) as well. We will keep you posted but you can also follow the issue by adding your +1 there :)

**Comment by askulkarni2** [comment] 2022-04-20 06:38
After rerunning the cloud-init my node seems fine, although EKS is still reporting the node group failed to join.

```sh
▶ k get pods -A
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   aws-node-bnsrv            1/1     Running   0          94m
kube-system   coredns-f47955f89-djlgz   1/1     Running   0          100m
kube-system   coredns-f47955f89-tpl25   1/1     Running   0          100m
kube-system   kube-proxy-7gh4h          1/1     Running   0          94m


▶ k get nodes
NAME                                        STATUS   ROLES    AGE   VERSION
ip-10-0-12-184.us-east-2.compute.internal   Ready    <none>   94m   v1.21.5-eks-9017834

▶ k get cm aws-auth -n kube-system -o yaml
apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::XXXXXXXXX:role/aws-preprod-dev-eks-ondemand_v1"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-20T04:57:25Z"
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-eks-blueprints
  name: aws-auth
  namespace: kube-system
  resourceVersion: "913"
  uid: 34cff032-8f26-4498-a22c-f9da2cabb88f
```

**Comment by spkane** [comment] 2022-04-20 11:56
@askulkarni2 Thank you for looking into this. I am really glad to know that this isn't just me.

A few things:

- The problem with the node group never showing up as healthy, once the initial failure occurs, is a know AWS issue that is on their roadmap. We should all +1 it.
  - https://github.com/aws/containers-roadmap/issues/764

- I am having trouble tracing the blueprints terraform code and even understanding where the upstream managed node module is getting called. It appears to me that you all are using your own module. What bit of logic am I missing here?

- I ran into the issue with the `bootstrap.sh` script but did not know there was an issue already. That script is not currently idemoptent, because it runs an `mv` command instead of a `cp` command for the iptables.
  - https://github.com/awslabs/amazon-eks-ami/pull/893
  - This is a problem, but fixing it would only mask the underlying problem, which appears to be that [this user-data template](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/linux_user_data.tpl) is getting used incorrectly and creating a bad user-data script with two bootstrap commands in it.

- Also, did you see the multiple node groups created? If so, any idea how that is happening? Maybe because both modules are duplicating a step?
  - One of these launch groups has a good user-data script, but the other does not, yet the bad one is used. I think somehow the modules are both creating a launch template and this is part of the issue.

**Comment by spkane** [comment] 2022-04-20 12:03
I think the most useful next step would be to understand:

- How is this template being pulled in? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/linux_user_data.tpl
- And in that template, why is `enable_bootstrap_user_data` true, when it defaults to false and doesn't appear to be set anywhere.

**Comment by spkane** [comment] 2022-04-20 12:23
Making some progress. Creating a minimal managed node group with this definition works fine:

```hcl
managed_node_groups = {
  ondemand_v1 = {
    node_group_name = "ondemand_v1"

    //create_launch_template  = true
    //launch_template_os      = "amazonlinux2eks"

    //instance_types = ["m5.8xlarge"]
    instance_types = ["t3a.large"]
    //subnet_type    = "private"
    //ami_type       = "AL2_x86_64"
    //capacity_type  = "ON_DEMAND"
    //disk_size      = 50

    //desired_size    = 1
    min_size        = 1
    //max_size        = 4
    max_unavailable = 1
  }
}
```

and results in this single launch template:

![CleanShot 2022-04-20 at 05 19 24](https://user-images.githubusercontent.com/129629/164228992-27a8dece-cd64-47c1-a941-c7b918762bf8.png)

with this contents:

```bash
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=AAAA==
API_SERVER_URL=https://AAA.gr7.us-east-1.eks.amazonaws.com
K8S_CLUSTER_DNS_IP=172.20.0.10
/etc/eks/bootstrap.sh trilambs-sbox-poc2-eks --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-05a282ba7e9059211,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=ondemand_v1-20220420121245938700000005' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP

--//--
```

which I am pretty sure is created by the upstream module's code.

**Comment by spkane** [comment] 2022-04-20 12:39
Changing the managed node group to this:

```hcl
managed_node_groups = {
  ondemand_v1 = {
    node_group_name = "ondemand_v1"

    create_launch_template  = true
    launch_template_os      = "amazonlinux2eks"

    //instance_types = ["m5.8xlarge"]
    instance_types = ["t3a.large"]
    //subnet_type    = "private"
    //ami_type       = "AL2_x86_64"
    //capacity_type  = "ON_DEMAND"
    //disk_size      = 50

    //desired_size    = 1
    min_size        = 1
    //max_size        = 4
    //max_unavailable = 1
  }
}
```

results in two launch templates and now things are broken:

![CleanShot 2022-04-20 at 05 38 15](https://user-images.githubusercontent.com/129629/164232167-510cbc15-aff4-4ac4-bc99-6946024fce91.png)

**Comment by bryantbiggs** [comment] 2022-04-20 13:11
Hi @spkane - hopefully I can help clarify a few details. 

This module only uses the upstream terraform-aws-eks control plane - it does not use the upstream functionality for creating self managed node groups, EKS managed node groups, or fargate profiles. 

The user data that this module users for EKS managed node groups can be found here https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/aws-eks-managed-node-groups/templates

When  using the EKS managed node group, there are a few scenarios to consider with launch templates:
- By default, the EKS managed node group service will create its own launch template. This is what you are seeing [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/428#issuecomment-1103870540)
- When you tell the module to create a launch template, that launch template will be merged with the launch template created by the EKS managed node group service. This is why you will see 2 launch templates when you specify `create_launch_template = true`. This is also where the user data is merged between the user supplied launch template and the user data supplied by the EKS managed node group service. The user data the EKS managed node group service provides is only the bootstrap script invocation to join the node to the control plane and is the last portion of the MIME multi-part script text
- If a user specifies an `ami_id` when using the EKS managed node group service, the bootstrap script user data MUST be supplied because the EKS managed node group service will not supply it and merge it into the user data. That is where these templates come into play https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/aws-eks-managed-node-groups/templates

**Comment by spkane** [comment] 2022-04-20 13:30
Thank you @bryantbiggs those details do help make the underlying decision tree clearer.

So, it appears that the merge is what is causing the issue.

One launch template looks like this:

```bash
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex

# User-supplied pre userdata code


# Bootstrap and join the cluster
/etc/eks/bootstrap.sh --b64-cluster-ca 'AAA==' --apiserver-endpoint 'https://AAA.gr7.us-east-1.eks.amazonaws.com'  --kubelet-extra-args "" 'foo-sbox-poc2-eks'

# User-supplied post userdata code


--//--
```


and the other one that actually gets used looks like this:

```bash
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex

# User-supplied pre userdata code


# Bootstrap and join the cluster
/etc/eks/bootstrap.sh --b64-cluster-ca 'AAA==' --apiserver-endpoint 'https://AAA.gr7.us-east-1.eks.amazonaws.com'  --kubelet-extra-args "" 'foo-sbox-poc2-eks'

# User-supplied post userdata code


--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=AAA==
API_SERVER_URL=https://AAA.gr7.us-east-1.eks.amazonaws.com
K8S_CLUSTER_DNS_IP=172.20.0.10
/etc/eks/bootstrap.sh foo-sbox-poc2-eks --kubelet-extra-args '--node-labels=eks.amazonaws.com/sourceLaunchTemplateVersion=1,eks.amazonaws.com/nodegroup-image=ami-05a282ba7e9059211,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=ondemand_v1-20220420130614890600000001,eks.amazonaws.com/sourceLaunchTemplateId=lt-0f9b98db4d23059b2' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP


--//--
```

Which now, actually makes me think that the fix is to modify this template (and maybe the other ones) in this blueprints repo to REMOVE the `bootstrap.sh` call.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/aws-eks-managed-node-groups/templates/userdata-amazonlinux2eks.tpl

Maybe, there needs to be a different template when one is providing an AMI and must include `bootsrap.sh` and when one is just using the default AMI?

**Comment by spkane** [comment] 2022-04-20 13:53
This change in the template worked around my immediate issue.

https://github.com/spkane/terraform-aws-eks-blueprints/compare/main...mng-launch-templates

But I think that line is required when one is providing their own AMI, so there likely needs to be some logic to detect when someone passes in an AMI that determines which template to use.

**Comment by spkane** [comment] 2022-04-20 16:16
Thank you @vara-bonthu ! I really appreciate it. I could have pulled the PR together, but honestly, this took long enough to track down that I need to focus on my project's more immediate goal for a few days.

**Comment by vara-bonthu** [comment] 2022-04-20 16:18
I am running some final tests to ensure if it works for all scenarios. We will raise a PR soon.

**Closed** 2022-04-23 13:47 UTC
Labels: bug
