### ISSUE TITLE
FluxCD GitOps Integration

### ISSUE THREAD

**Issue by williamsbobby1423** [aws-ia/terraform-aws-eks-blueprints#1554] opened 2023-04-17 14:15 UTC
A request to enhance blueprints deployment options by adding an addon for [FluxCD](https://fluxcd.io/flux/) which will allow users to use FluxCD to manage their GitOps workflow. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bryantbiggs** [comment] 2023-04-17 14:35
duplicate of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/26

Please feel free to add any feedback to this issue if interested https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114

**Closed by bryantbiggs** 2023-04-17 14:35 UTC
