### ISSUE TITLE
Pin a version from Terraform source

### ISSUE THREAD

**Issue by ir-vsem** [aws-ia/terraform-aws-eks-blueprints#1408] opened 2023-02-03 17:31 UTC
- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

Hi is there are was to pin to a version of a release?
I'd like to do something like the following

```
module "example {
    source = "github.com/aws-ia/terraform-aws-eks-blueprints"
    version = "4.22.0"
   .
   .
   ....
}  
```  

Thank you,
Virath

**Comment by ir-vsem** [comment] 2023-02-03 17:40
I should add that I'm doing this now;
`source = "github.com/aws-ia/terraform-aws-eks-blueprints.git?ref=v4.22.0"`

**Comment by bryantbiggs** [comment] 2023-02-03 17:58
Duplicate of #1394

**Closed by bryantbiggs** 2023-02-03 17:58 UTC
