### ISSUE TITLE
Minimum IAM Policy insufficient

### ISSUE THREAD

**Issue by timblaktu** [aws-ia/terraform-aws-eks-blueprints#902] opened 2022-08-28 02:51 UTC
## Description

I'm getting "not authorized to perform" errors in the `terraform apply -target=module.eks_blueprints` stage:

```
Error: error creating IAM OIDC Provider: AccessDenied: User: arn:aws:iam::053733570179:user/tim is not authorized to perform: iam:TagOpenIDConnectProvider on resource: arn:aws:iam::053733570179:oidc-provider/oidc.eks.us-west-2.amazonaws.com because no identity-based policy allows the iam:TagOpenIDConnectProvider action

Error: error creating EKS Node Group (cluster-prototype-tim:managed-ondemand-20220828003905172200000009): AccessDeniedException: User: arn:aws:iam::053733570179:user/tim is not authorized to perform: eks:TagResource on resource: arn:aws:eks:us-west-2:053733570179:cluster/cluster-prototype-tim
```

The AWS identity running terraform has a single managed policy attached, that is almost exactly the [latest published Min IAM Policy doc](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/iam/min-iam-policy.json) generated by iamlive in your e2e workflow, having the following seemingly-unrelated changes which were recommended by the AWS IAM JSON Editor's Linter:

1. Removed s3:DeleteBucketOwnershipControls
    a. This appears to only is used in the [velero backup example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/710762bcb431878b7d2394feec52f44b8f7a4ad8/examples/stateful/main.tf#L145), and I'm not using the velero addon in my config.
2. Removed iam:CreateServiceLinkedRole
    a. `aws_iam_service_linked_role` only appears to declared in [this example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/710762bcb431878b7d2394feec52f44b8f7a4ad8/examples/observability/amp-amg-opensearch/main.tf#L178) and I'm not using any of the fluentbit/opensearch/observability stuff.
3. Changed the Resources for `iam:PassRole` from `*` to the 2 specific resource patterns that were found to be used in my local iamlive  "proxy recordings":
    - "arn:aws:iam::053733570179:role/*-*-cluster-role",
    - "arn:aws:iam::053733570179:role/*-*-managed-ondemand"

Only when I added the missing permissions indicated in the errors reported above (`iam:TagOpenIDConnectProvider *` and `eks:TagResource *`) to the policy, my full terraform apply/destroy cycle completed without another error.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

1.2.7
- Provider version(s):

main     | - Using previously-installed gavinbunney/kubectl v1.14.0                                                                                                                                                  main     | - Using previously-installed hashicorp/aws v4.27.0
main     | - Using previously-installed hashicorp/cloudinit v2.2.0                                                                                                                                                   main     | - Using previously-installed hashicorp/time v0.8.0                                                                                                                                                        main     | - Using previously-installed hashicorp/local v2.2.3
main     | - Using previously-installed hashicorp/helm v2.6.0                                                                                                                                                        main     | - Using previously-installed terraform-aws-modules/http v2.4.1                                                                                                                                            main     | - Using previously-installed hashicorp/tls v3.4.0                                                                                                                                                         main     | - Using previously-installed hashicorp/random v3.3.2                                                                                                                                                      main     | - Using previously-installed hashicorp/null v3.1.1                                                                                                                                                        main     | - Using previously-installed hashicorp/kubernetes v2.13.0                                                                                                                                                 

## Reproduction Code [Required]

Here's  my main.tf. The rest of the project is a simple merge of the argocd/crossplane example projects. Nothing special.

```
data "aws_eks_cluster_auth" "this" {
  name = module.eks_blueprints.eks_cluster_id
}

data "aws_availability_zones" "available" {}

locals {
  # EKS Blueprints embeds local.name in all resources' `Name` tag.
  # Here, we make this unique and environment/workspace-specific.
  name   = join("-", [basename(path.cwd), terraform.workspace])

  # TODO: shouldn't region come from the profile used, and/or AWS_REGION env var?
  region = "us-west-2"

  vpc_cidr = "10.0.0.0/16"
  azs      = slice(data.aws_availability_zones.available.names, 0, 3)

  # EKS Blueprints already uses local.name as prefix or suffix in resource `Name` tag,
  #   so ATM we do not need further distinction.
  tags = {
    # Blueprint = local.name
  }
}

#---------------------------------------------------------------
# EKS Blueprints
#---------------------------------------------------------------

module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.7.0"

  cluster_name    = local.name
  cluster_version = "1.23"

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  managed_node_groups = {
    mg_5 = {
      node_group_name = "managed-ondemand"
      instance_types  = ["t3.medium"]
      # instance_types  = ["m5.large"]
      min_size        = 2
      max_size        = 5
      subnet_ids      = module.vpc.private_subnets
    }
  }

  tags = local.tags
}

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.7.0"

  eks_cluster_id       = module.eks_blueprints.eks_cluster_id
  eks_cluster_endpoint = module.eks_blueprints.eks_cluster_endpoint
  eks_oidc_provider    = module.eks_blueprints.oidc_provider
  eks_cluster_version  = module.eks_blueprints.eks_cluster_version

  #############################################################################
  # ARGO CD CONFIG
  enable_argocd = true
  # This example shows how to set default ArgoCD Admin Password using SecretsManager with Helm Chart set_sensitive values.
  argocd_helm_config = {
    set_sensitive = [
      {
        name  = "configs.secret.argocdServerAdminPassword"
        value = bcrypt(data.aws_secretsmanager_secret_version.admin_password_version.secret_string)
      }
    ]
  }
  # Indicates that ArgoCD is responsible for managing/deploying add-ons
  argocd_manage_add_ons = true
  # Repositories watched by Argo CD
  argocd_applications = {
    # addons and workloads are sample GitOps configuration repositories set up for Blueprints Demos
    # Addons follows the Argo CD "app of apps" pattern to bootstrap cluster with k8s addons
    addons = {
      path               = "chart"
      repo_url           = "https://github.com/aws-samples/eks-blueprints-add-ons.git"
      add_on_application = true  # indicates the "root" addon application.
                                 # If provided, the type must be set to "helm" for the root add-on application.
      # ssh_key_secret_name = "github-ssh-key"  # Needed for private repos
      # values              = {}
      # type                = "helm"            # Optional, defaults to helm.
    }
  }

  #############################################################################
  # CROSSPLANE CONFIG
  enable_crossplane = true
  # You can choose to install either of crossplane_aws_provider or crossplane_jet_aws_provider to work with AWS
  # Creates ProviderConfig -> aws-provider
  crossplane_aws_provider = {
    enable               = true
    provider_aws_version = "v0.24.1"
    # NOTE: Crossplane requires Admin like permissions to create and update resources similar to Terraform deploy role.
    # This example config uses AmazonS3FullAccess for demo purpose only, but you should select a policy with the minimum permissions required to provision your resources.
    additional_irsa_policies = ["arn:aws:iam::aws:policy/AmazonS3FullAccess"]
  }
  # Creates ProviderConfig -> jet-aws-provider
  crossplane_jet_aws_provider = {
    enable               = true
    provider_aws_version = "v0.4.1"
    # NOTE: Crossplane requires Admin like permissions to create and update resources similar to Terraform deploy role.
    # This example config uses AmazonS3FullAccess for demo purpose only, but you should select a policy with the minimum permissions required to provision your resources.
    additional_irsa_policies = ["arn:aws:iam::aws:policy/AmazonS3FullAccess"]
  }

  tags = local.tags
}

#---------------------------------------------------------------
# ArgoCD Admin Password credentials with Secrets Manager
# Login to AWS Secrets manager with the same role as Terraform to extract the ArgoCD admin password with the secret name as "argocd"
#---------------------------------------------------------------
resource "random_password" "argocd" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

#tfsec:ignore:aws-ssm-secret-use-customer-key
resource "aws_secretsmanager_secret" "arogcd" {
  name                    = "argocd-${local.name}"
  recovery_window_in_days = 0  # Set to zero for this example to force delete during Terraform destroy
}

resource "aws_secretsmanager_secret_version" "arogcd" {
  secret_id     = aws_secretsmanager_secret.arogcd.id
  secret_string = random_password.argocd.result
}

data "aws_secretsmanager_secret_version" "admin_password_version" {
  secret_id = aws_secretsmanager_secret.arogcd.id

  depends_on = [aws_secretsmanager_secret_version.arogcd]
}

#---------------------------------------------------------------
# Supporting Resources
#---------------------------------------------------------------

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = local.name
  cidr = local.vpc_cidr

  azs             = local.azs
  public_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k)]
  private_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 10)]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  # Manage so we can name
  manage_default_network_acl    = true
  default_network_acl_tags      = { Name = "${local.name}-default" }
  manage_default_route_table    = true
  default_route_table_tags      = { Name = "${local.name}-default" }
  manage_default_security_group = true
  default_security_group_tags   = { Name = "${local.name}-default" }

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/elb"              = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/internal-elb"     = 1
  }

  tags = local.tags
}
```

```
export ENVIRONMENT=foo  # doesn't matter, but must be set. This becomes the workspace and is embedded in resource names
terraform workspace select "${ENVIRONMENT}" || terraform workspace new "${ENVIRONMENT}" || true                                                                                                                      TF_WORKSPACE="${ENVIRONMENT}" terraform init
terraform workspace select "${ENVIRONMENT}" || terraform workspace new "${ENVIRONMENT}" || true
time terraform apply -target=module.vpc -no-color -input=false -auto-approve -compact-warnings 
time terraform apply -target=module.eks_blueprints -no-color -input=false -auto-approve -compact-warnings 
time terraform apply -target=module.eks_blueprints_kubernetes_addons -no-color -input=false -auto-approve -compact-warnings 

echo "waiting a minute before destroying..."
sleep 60

time terraform destroy -target="module.eks_blueprints_kubernetes_addons" -input=false -auto-approve -compact-warnings 
time terraform destroy -target="module.eks_blueprints" -input=false -auto-approve -compact-warnings 
time terraform destroy -target="module.vpc" -input=false -auto-approve -compact-warnings 
```

## Expected behavior

I expected to use the min iam policy (with minor changes that are irrelevant to my config) and fully apply and destroy eks blueprints.

## Actual behavior

See Description.

### Terminal Output Screenshot(s)

See Description.

## Additional context

I am an iamlive user, and understand that this could simply be an error in that tool. I just wanted to provide this as feedback on your policy generation process, so we can refine it to make sure it's as accurate as possible. I typically use proxy mode, with terraform/aws running in one container, and iamlive in another container in proxy mode, and would be happy to help troubleshoot and/or improve the system if necessary.

I noticed that [your docs on the min iam policy](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/iam/minimum-iam-policy.md#how-this-policy-was-generated) indicate that you're running iamlive in CSM mode. I know that CSM and proxy modes are different in terms of their capture technique and the resolution or granularity of its "recordings". I only mention this because I wonder if the discrepancy I reported might be due to using CSM mode in your process.

I suppose some good steps would be for:
* me to see if my iamlive proxy system can reproduce the same policy document as your e2e workflow.. 
* you to try to repro my errors with your min iam policy doc and my config.

**Comment by Zvikan** [comment] 2022-08-30 15:48
Hey, thank you for detailed issue!

There's a good chance that the tool is missing these 2 actions, I am not sure if it's related cause of using CSM instead of proxy, the reason for using proxy originally was to keep things simple and avoid any proxy settings (especially for the helm repos that needs to be added to an "allowlist").
I see that you replied to the [same issue](https://github.com/iann0036/iamlive/issues/51) I found in the iamlive repo, as you mentioned in the additional context, we should test your example while running iamlive in the background and see the results.

I was also checking the [e2e results](https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/8027076040?check_suite_focus=true) when I updated examples to version 1.23 recently, both `iam:TagOpenIDConnectProvider` and `eks:TagResource` not reported in the final merged output.
Checking iamlive, there's a new release (0.49.0) but I don't see any new mapping or updates around these 2 API calls, worth testing with the latest version anyway.

If you can run iamlive with the same setup we have in our workflow and provide the output policy we can see if it's indeed upstream issue that we should raise with iamlive.

**Comment by Zvikan** [comment] 2022-08-30 17:36
Ok so I ran a quick test with `TF_TRACE` enabled for the following tf snippet:
```hcl
resource "aws_iam_openid_connect_provider" "default" {
  url = "https://accounts.google.com"

  client_id_list = [
    "blabla.googleusercontent.com",
  ]

  thumbprint_list = []
  tags = ({Hello = "world", test = "test" , a="b", c="d"})
}

```

There's no API call for `TagOpenIDConnectProvider` as expected, and after reading the [official API docs](https://docs.aws.amazon.com/IAM/latest/APIReference/API_TagOpenIDConnectProvider.html) it got me thinking that this API will only happen if we update (AKA "add") new tag, as the first apply that we do is just a create where we pass the tags, and this is how our current E2E is design (single apply, we're not updating any tags and re-applying).

I confirmed this by running the above snippet also with iamlive, it didn't print out `TagOpenIDConnectProvider`, but when I added a new tag to the map, and re-applied, iamlive did print out `TagOpenIDConnectProvider`.

I assume this may be true also for `TagResource` , right now not updating the code and running terraform again using our e2e workflow, this should probably be an improvement to how we run the e2e (I don't see an easy way to modify attributes and then re-apply terraform to now capture all the extra APIs that are not called on the first TF apply...).

As a short term, we should manually add these actions that you captured to our docs, and add a note that this list of actions captured by iamlive assumes a single success of terraform apply and not update to the attributes, we can link to this issue to share an example where it can happen. what do you think?

**Comment by timblaktu** [comment] 2022-09-03 23:49
@Zvikan thanks for your close attention to this. What you propose sounds good. I'll be back to work next week, extending our usage of this terraform project, and will monitor generated iam policies as we go and report any addition information i have.

**Closed** 2022-11-14 17:53 UTC
Labels: bug, documentation, upstream issue
