### ISSUE TITLE
[FEATURE] Opentemetry Operator / ADOT - Allow use `cert-manager` helm release outside of `opentelemetry-operator` module

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#826] opened 2022-08-07 23:23 UTC
#### Is your feature request related to a problem? Please describe
Cert-manager is a very important addon to help manage certificates within a cluster. It may already be installed via the `cert-manager` module. Mandatory installation of this addon in the `opentelemetry-operator` module may cause installation/configuration conflicts on existing EKS clusters.

#### Describe the solution you'd like
We could have 1 helm_release that install the addon along with `cert-manager` and 1 `helm_release` that will install with `cert-manager` installed outside the `opentelemetry-operator` module

`modules/kubernetes-addons/opentelemetry-operator/main.tf`

```hcl
module "cert_manager" {
  source = "../cert-manager"
  count  = var.internal_cert_manager && !var.external_cert_manager ? 1 : 0

  # https://docs.aws.amazon.com/eks/latest/userguide/adot-reqts.html
  # certmanaager v1.6.0 onwards is not supported yet
  helm_config   = { version = "v1.5.0" }
  addon_context = var.addon_context
}

module "helm_addon_internal_cert_manager" {
  source = "../helm-addon"
  count  = var.enable_opentelemetry_operator && var.internal_cert_manager && !var.external_cert_manager ? 1 : 0

  helm_config   = local.helm_config
  irsa_config   = null
  addon_context = var.addon_context

  depends_on = [module.cert_manager]
}

module "helm_addon_external_cert_manager" {
  source = "../helm-addon"
  count  = var.enable_opentelemetry_operator && var.external_cert_manager && !var.internal_cert_manager ? 1 : 0

  helm_config   = local.helm_config
  irsa_config   = null
  addon_context = var.addon_context
}
```
#### Additional context
As a consequence, there is a risk of the user enabling the installation of `opentelemetry-operator` with the option of external cert manager, but without it installed.

**Comment by bryantbiggs** [comment] 2022-08-09 20:14
duplicate of #757 - please check existing issues before opening new

**Closed by bryantbiggs** 2022-08-09 20:14 UTC
